version: '3.4'

services:

  postgres:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    volumes:
      - ./docker/database/_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: auth-api
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
      target: prod
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always

  frontend:
    container_name: auth-ui
    build:
      context: ./ui
      dockerfile: ../docker/ui/Dockerfile
      target: prod
    ports:
      - "5000:80"
    restart: always