version: '3.1'

services:

  postgres:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    volumes:
      - ./docker/database/_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"